- op: replace
  path: /spec/providerSpec/value/platform
  value:
    type: "gce"
    config: |
      zone: "us-central1-c"
      project: "{{PROJECT_NAME}}"
      instances:
        type:  "n1-standard-1"
        image: "https://www.googleapis.com/compute/v1/projects/{{PROJECT_NAME}}/global/images/{{TALOS_IMAGE_NAME}}"
        disks:
          size: 10